<?php
$form->setAttributes ( array (
    'action' => $this->url('root'),
    'method' 	=> 'post',
    'class' 	=> 'form-horizontal',
    'id'	=> 'loginForm',
) );
$form->prepare ();
?>
<div class="panel panel-default text-center">
  <div class="panel-heading">
    <h3 class="panel-title">Login</h3>
  </div>
  <div class="panel-body">
    <section id="loginFormSection">
        <?= $this->form ()->openTag ( $form );?> 
            <div class="form-group">
                <?=  $this->formElement($form->get('Email')); ?>   
                <?=  $this->formElementErrors($form->get('Email')); ?> 
            </div>
            <div class="form-group">
                <?= $this->formElement($form->get('Password')); ?>   
                <?= $this->formElementErrors($form->get('Password')); ?> 
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
                &nbsp;&nbsp;<a href="<?=$this->url('root',array('action' => 'register'))?>">Register</a>
            </div>
        <?= $this->form ()->closeTag ();?><!-- form -->
    </section><!-- content -->
  </div>
</div>
