<?php
$form->setAttributes ( array (
    'action' => $this->url('root',array('action'=>'register')),
    'method' 	=> 'post',
    'class' 	=> 'form-horizontal',
    'id'	=> 'registerForm',
) );
$form->prepare ();
?>

<div class="panel panel-default text-center">
  <div class="panel-heading">
    <h3 class="panel-title">Register</h3>
  </div>
  <div class="panel-body">
    <section id="loginFormSection">
        <?= $this->form ()->openTag ( $form );?> 
           <div class="form-group">
                <?= $this->formElement($form->get('FirstName')); ?>
                <?= $this->formElementErrors($form->get('FirstName')); ?> 
            </div>
           <div class="form-group">
                <?= $this->formElement($form->get('LastName')); ?>   
                <?= $this->formElementErrors($form->get('LastName')); ?> 
            </div>
           <div class="form-group">
                <?= $this->formElement($form->get('Email')); ?>   
                <?= $this->formElementErrors($form->get('Email')); ?> 
            </div>
           <div class="form-group">
                <?= $this->formElement($form->get('Password')); ?>   
                <?= $this->formElementErrors($form->get('Password')); ?> 
            </div>
           <div class="form-group">
                <?= $this->formElement($form->get('repassword')); ?>   
                <?= $this->formElementErrors($form->get('repassword')); ?> 
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
                &nbsp;&nbsp;<a href="<?=$this->url('root')?>">Login</a>
            </div>
        <?= $this->form ()->closeTag ();?><!-- form -->
    </section><!-- content -->
  </div>
</div>
<div class="container">

</div><!-- container -->